name: Prepare Docker image for building onnxruntime

on:
  # Run when the image builder changes
  push:
    branches:
      - master

jobs:
  create-builder:
    runs-on: ubuntu-20.04
    steps:
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: docker/build-push-action@v2
        with:
          push: true
          tags: pitop/onnxruntime-builder:latest
          file: Dockerfile.builder
